### ISSUE TITLE
CI Pipeline not running acceptance tests

### ISSUE THREAD

**Issue by Druage** [FordLabs/retroquest#46] opened 2018-07-12 14:23 UTC
## Bug report
Travis CI pipeline isn't running our UI acceptance tests (npm run e2e). A pull request that was merged broke some of these.

Acceptance Criteria - Fix the tests and have Travis run them on push.

**Comment by Druage** [comment] 2018-07-12 18:17
The issue is still standing even with the PR we put in

**Comment by mikesmithson** [comment] 2020-07-29 15:25
e2e tests were fixed in develop. However, to run this in CI using the npm task, you would also have to start up the SpringBoot backend container in a daemon process in the CI pipeline, run the tests, and then shut down the container. Would this be better if the e2e tests were run in a SpringBoot-type test with the whole app (ui,api components) deployed and running?

**Comment by lndobryden** [comment] 2021-05-27 20:21
Since we've moved to GitHub actions and cypress for acceptance tests more recently, I think we'll close this as a duplicate of #292

**Closed by lndobryden** 2021-05-27 20:21 UTC
Labels: internally assigned
